from __future__ import annotations

import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tarfile
from types import SimpleNamespace

import pytest

import isolated_full_test_gate as gate


def test_gate_policy_is_the_existing_manual_full_suite_command():
    from skybuild.manual_integration import DEFAULT_GATE_COMMAND, DEFAULT_GATE_COMMAND_SHA256

    assert gate.DEFAULT_GATE_COMMAND == DEFAULT_GATE_COMMAND
    assert gate.DEFAULT_GATE_COMMAND_SHA256 == DEFAULT_GATE_COMMAND_SHA256


def test_candidate_environment_contains_only_synthetic_database_credentials():
    environment = gate._candidate_environment("synthetic-password")

    assert sorted(environment) == sorted(gate.ENV_ALLOWLIST)
    assert environment["SKYBUILD_TEST_DSN"] == (
        "postgresql://postgres:synthetic-password@db:5432/skybuild_test"
    )
    assert environment["UV_NO_SYNC"] == "1"
    assert environment["UV_OFFLINE"] == "1"
    assert all("TOKEN" not in name and "SECRET" not in name and "KEY" not in name
               for name in environment)


def test_trusted_probe_environment_overrides_image_baked_dsns_and_host_values():
    environment = gate._trusted_probe_environment()

    assert sorted(environment) == sorted(gate.ENV_ALLOWLIST)
    assert environment["SKYBUILD_TEST_DSN"] == ""
    assert environment["SKYBUILD_GATE_HOST_GATEWAY"] == ""
    assert environment["SKYBUILD_GATE_HOST_LISTENER_PORT"] == ""


def test_saved_firewall_rules_accept_exact_filter_table_and_reject_extra_tables():
    value = """# Generated by iptables-save v1.8.9 (nf_tables) on today
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-A INPUT -i lo -j ACCEPT
COMMIT
# Completed on today
"""

    assert gate._saved_rules(value) == ["INPUT DROP", "FORWARD DROP", "OUTPUT DROP",
                                        "-A INPUT -i lo -j ACCEPT"]
    with pytest.raises(gate.GateError, match="unexpected table"):
        gate._saved_rules(value.replace("*filter", "*nat\n:PREROUTING ACCEPT [0:0]"))


def test_saved_firewall_rules_reject_user_defined_chains():
    value = """*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
:CUSTOM - [0:0]
COMMIT
"""

    with pytest.raises(gate.GateError, match="user-defined chain"):
        gate._saved_rules(value)


def test_firewall_policy_render_and_inspect_match_both_namespaces(monkeypatch):
    postgres_ip, candidate_ip = "172.18.0.2", "172.18.0.3"

    def saved(postgres_namespace, ipv6):
        expected = gate._expected_firewall_rules(postgres_ip, candidate_ip,
                                                ipv6=ipv6, postgres_namespace=postgres_namespace)
        lines = ["*filter"]
        lines.extend(":" + row.split()[0] + " " + row.split()[1] + " [0:0]"
                     for row in expected[:3])
        lines.extend(expected[3:])
        lines.append("COMMIT")
        return "\n".join(lines) + "\n"

    calls = []
    current_namespace = [False]

    def docker(*args, **kwargs):
        calls.append(args)
        return subprocess.CompletedProcess(args, 0,
            saved(current_namespace[0], args[-1] == "ip6tables-save"), "")

    monkeypatch.setattr(gate, "_docker", docker)
    for postgres_namespace in (False, True):
        current_namespace[:] = [postgres_namespace]
        evidence = gate._verify_firewall_rules("a" * 64, postgres_ip, candidate_ip,
                                               postgres_namespace=postgres_namespace)
        assert evidence == {"firewall_defaults_drop": True,
                            "firewall_ipv4_default_drop": True,
                            "firewall_ipv6_default_drop": True,
                            "firewall_policy_applied": True}
    assert len(calls) == 4


def test_postgres_inspection_requires_exact_tmpfs_and_no_extra_mounts():
    container_id = "a" * 64
    image_id = "sha256:" + "b" * 64
    network = "isolated-net"
    destinations = ("/var/lib/postgresql/data", "/var/run/postgresql", "/tmp")
    row = {
        "Id": container_id, "Name": "/postgres-run", "Image": image_id,
        "Config": {"Labels": {gate.RUN_ID_LABEL: "run", gate.KIND_LABEL: "postgres"},
                   "User": "999:999"},
        "HostConfig": {
            "NetworkMode": network, "Memory": 1536 * 1024**2,
            "MemorySwap": 1536 * 1024**2, "NanoCpus": 1_000_000_000,
            "PidsLimit": 128, "PortBindings": {}, "ReadonlyRootfs": True,
            "LogConfig": {"Type": "local", "Config": {"max-size": "32m", "max-file": "1"}},
            "CapAdd": [], "CapDrop": ["ALL"], "SecurityOpt": ["no-new-privileges:true"],
            "Tmpfs": {
                destinations[0]: "rw,nosuid,nodev,noexec,size=1073741824,uid=999,gid=999,mode=448",
                destinations[1]: "rw,nosuid,nodev,noexec,size=16777216,uid=999,gid=999,mode=2045",
                destinations[2]: "rw,nosuid,nodev,noexec,size=134217728,uid=999,gid=999,mode=1023",
            },
        },
        "Mounts": [{"Type": "tmpfs", "Destination": path, "RW": True} for path in destinations],
        "NetworkSettings": {"Networks": {network: {"NetworkID": "c" * 64}}},
    }

    gate._check_postgres_inspect(row, name="postgres-run", run_id="run",
                                 container_id=container_id, image_id=image_id, network=network)
    row["Mounts"].append({"Type": "bind", "Destination": "/host", "RW": False})
    with pytest.raises(gate.GateError):
        gate._check_postgres_inspect(row, name="postgres-run", run_id="run",
                                     container_id=container_id, image_id=image_id, network=network)


def test_attestation_key_preflight_requires_owned_mode_0600_key(tmp_path):
    key = tmp_path / "key"
    key.write_bytes(b"k" * 32)
    key.chmod(0o600)

    gate._validate_attestation_key(key, "runner-key-1")
    key.chmod(0o640)
    with pytest.raises(gate.GateError, match="mode 0600"):
        gate._validate_attestation_key(key, "runner-key-1")


def test_signer_receives_keyword_key_arguments(monkeypatch, tmp_path):
    key = tmp_path / "key"
    key.write_bytes(b"k" * 32)
    key.chmod(0o600)
    seen = {}

    def sign(predicate, *, key_path, key_id):
        seen.update(predicate=predicate, key_path=key_path, key_id=key_id)
        return {"signed": True}

    monkeypatch.setitem(sys.modules, "trusted_gate_attestation", SimpleNamespace(sign_attestation=sign))
    predicate = {"result": 0}
    assert gate._sign_receipt(predicate, key, "key-1") == {"signed": True}
    assert seen == {"predicate": predicate, "key_path": key, "key_id": "key-1"}


def test_archive_extraction_rejects_parent_traversal(tmp_path):
    archive = tmp_path / "unsafe.tar"
    with tarfile.open(archive, "w") as stream:
        member = tarfile.TarInfo("../escape")
        member.size = 4
        stream.addfile(member, io.BytesIO(b"oops"))

    with pytest.raises(gate.GateError, match="unsafe member"):
        gate._extract_archive(archive, tmp_path / "out")
    assert not (tmp_path / "escape").exists()


def test_archive_extraction_rejects_symlink_members(tmp_path):
    archive = tmp_path / "unsafe.tar"
    with tarfile.open(archive, "w") as stream:
        link = tarfile.TarInfo("link")
        link.type = tarfile.SYMTYPE
        link.linkname = "/etc/passwd"
        stream.addfile(link)

    with pytest.raises(gate.GateError, match="unsafe member"):
        gate._extract_archive(archive, tmp_path / "out")


def _candidate_row(tmp_path):
    archive = tmp_path / "source"
    archive.mkdir()
    fixture = tmp_path / "entrypoint.py"
    fixture.write_text("runner", encoding="utf-8")
    probe = tmp_path / "network_probe.py"
    probe.write_text("probe", encoding="utf-8")
    env = gate._candidate_environment("pw")
    mounts = [
        {"Type": "bind", "Source": str(archive), "Destination": "/candidate", "RW": False},
        {"Type": "tmpfs", "Source": "", "Destination": "/scratch", "RW": True},
        {"Type": "bind", "Source": str(fixture), "Destination": "/runner/entrypoint.py", "RW": False},
        {"Type": "bind", "Source": str(probe), "Destination": "/runner/network_probe.py", "RW": False},
    ]
    env_list = [name + "=" + value for name, value in env.items()]
    row = {
        "Id": "a" * 64,
        "Name": "/candidate-run",
        "Image": "sha256:" + "b" * 64,
        "Config": {"Labels": {gate.RUN_ID_LABEL: "run", gate.KIND_LABEL: "candidate"},
                   "Cmd": gate.DEFAULT_GATE_COMMAND, "Entrypoint": ["/runner/entrypoint.py"],
                   "User": "10001:10001", "Env": env_list},
        "HostConfig": {"ReadonlyRootfs": True, "NetworkMode": "internal-net",
                       "Memory": 4 * 1024**3, "MemorySwap": 4 * 1024**3,
                       "NanoCpus": 2_000_000_000, "PidsLimit": 256,
                       "ShmSize": 256 * 1024**2, "Privileged": False,
                       "LogConfig": {"Type": "local", "Config": {"max-size": "128m", "max-file": "1"}},
                       "PidMode": "private", "IpcMode": "private", "PortBindings": {},
                       "Tmpfs": {"/scratch": "rw,noexec,nosuid,nodev,size=2147483648,uid=10001,gid=10001,mode=448"},
                       "ExtraHosts": ["db:172.18.0.3"],
                       "CapDrop": ["ALL"], "SecurityOpt": ["no-new-privileges:true"]},
        "Mounts": mounts,
        "NetworkSettings": {"Networks": {"internal-net": {"NetworkID": "c" * 64,
                                                                  "IPAddress": "172.18.0.3"}}},
    }
    return row, archive, fixture, probe, env


def test_candidate_inspection_accepts_only_exact_mount_and_environment_policy(tmp_path):
    row, archive, fixture, probe, env = _candidate_row(tmp_path)
    result = gate._check_candidate_inspect(
        row, name="candidate-run", run_id="run", container_id="a" * 64,
        image_id="sha256:" + "b" * 64, archive_root=archive, fixture_path=fixture,
        probe_path=probe, env=env, network="internal-net", archive_sha256="d" * 64,
        fixture_sha256="e" * 64, probe_sha256="f" * 64,
    )

    assert result["environment_allowlist"] == sorted(gate.ENV_ALLOWLIST)
    assert result["source_mount_readonly"] is True
    assert result["docker_socket_mounted"] is False
    assert result["host_credentials_mounted"] is False
    assert {item["source"] for item in result["mounts"]} == {
        "sha256:" + "d" * 64, "tmpfs", "sha256:" + "e" * 64, "sha256:" + "f" * 64
    }


@pytest.mark.parametrize("mutation", ["extra_mount", "extra_env", "port_bind", "extra_network", "privileged"])
def test_candidate_inspection_fails_closed_on_isolation_changes(tmp_path, mutation):
    row, archive, fixture, probe, env = _candidate_row(tmp_path)
    if mutation == "extra_mount":
        row["Mounts"].append({"Type": "bind", "Source": "/home/user", "Destination": "/home", "RW": False})
    elif mutation == "extra_env":
        row["Config"]["Env"].append("GH_TOKEN=private")
    elif mutation == "port_bind":
        row["HostConfig"]["PortBindings"] = {"5432/tcp": [{"HostPort": "5432"}]}
    elif mutation == "extra_network":
        row["NetworkSettings"]["Networks"]["bridge"] = {"NetworkID": "f" * 64}
    else:
        row["HostConfig"]["Privileged"] = True

    with pytest.raises(gate.GateError):
        gate._check_candidate_inspect(
            row, name="candidate-run", run_id="run", container_id="a" * 64,
            image_id="sha256:" + "b" * 64, archive_root=archive, fixture_path=fixture,
            probe_path=probe, env=env, network="internal-net", archive_sha256="d" * 64,
            fixture_sha256="e" * 64, probe_sha256="f" * 64,
        )


def test_container_create_inspection_error_does_not_claim_absence(monkeypatch):
    calls = []

    def docker(*args, **kwargs):
        calls.append(args)
        return subprocess.CompletedProcess(args, 1, "", "permission denied")

    monkeypatch.setattr(gate, "_docker", docker)
    with pytest.raises(gate.GateError, match="cannot be reconciled"):
        gate._container_info("owned-name", "run", None, "candidate")
    assert len(calls) == 1


def test_container_cleanup_reconciles_by_name_after_unknown_create(monkeypatch):
    owned = {
        "Id": "a" * 64, "Name": "/owned-name",
        "Config": {"Labels": {gate.RUN_ID_LABEL: "run", gate.KIND_LABEL: "candidate"}},
        "Image": "sha256:" + "b" * 64, "State": {"Running": False},
    }
    calls = []
    inspected = False

    def docker(*args, **kwargs):
        nonlocal inspected
        calls.append(args)
        if args[:3] == ("inspect", "--type", "container"):
            if not inspected:
                inspected = True
                return subprocess.CompletedProcess(args, 0, json.dumps([owned]), "")
            return subprocess.CompletedProcess(args, 1, "", f"Error: No such object: {args[-1]}")
        if args[0] == "rm":
            return subprocess.CompletedProcess(args, 0, "", "")
        raise AssertionError(args)

    monkeypatch.setattr(gate, "_docker", docker)
    journal = type("JournalStub", (), {"event": lambda *args, **kwargs: None})()
    assert gate._remove_container("owned-name", "run", None, "candidate", journal)
    assert any(call[0] == "rm" for call in calls)


def test_log_redaction_streams_and_hashes_without_persisting_password(monkeypatch, tmp_path):
    class FakeProcess:
        def __init__(self, command, *, stdout, stderr, preexec_fn):
            self.stdout = stdout
            stdout.write(b"prefix-synthetic-")
            stdout.write(b"password-suffix\n")

        def wait(self, timeout):
            return 0

    monkeypatch.setattr(gate.subprocess, "Popen", FakeProcess)
    log_path = tmp_path / "candidate.log"
    digest = gate._write_redacted_log("a" * 64, log_path, "synthetic-password")

    content = log_path.read_bytes()
    assert b"synthetic-password" not in content
    assert b"[REDACTED]" in content
    assert digest == hashlib.sha256(content).hexdigest()
    assert not log_path.with_suffix(".raw").exists()
